server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 🔥 ADD THIS (CRITICAL)
    location /patients {
        proxy_pass http://patient-service:3000;
    }

    location /visits {
        proxy_pass http://visit-service:3001;
    }

    # optional debug
    location /podname {
        return 200 "$hostname";
    }
}
