apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: {{ .Values.patient.service.type }}
  selector:
    app: patient
  ports:
    - name: http
      port: {{ .Values.patient.service.port }}
      targetPort: 3000
     
