apiVersion: v1
kind: Secret
metadata:
  name: hmis-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.mongoUser | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.mongoPassword | b64enc }}
